const SHOP_DATA = {
  watches: {
    id: 1,
    title: 'Watches',
    routeName: 'watches',
    items: [
      {
        id: 1,
        name: 'Watch 1',
        imageUrl: 'https://i.ibb.co/qD2xG1v/watch1.jpg',
        price: 25,
      },
      {
        id: 2,
        name: 'Watch 2 ',
        imageUrl: 'https://i.ibb.co/bHdntxb/watch2.jpg',
        price: 18,
      },
      {
        id: 3,
        name: 'Watch 3 ',
        imageUrl: 'https://i.ibb.co/Yymq1LW/watch3.jpg',
        price: 35,
      },
      {
        id: 4,
        name: 'Watch 4',
        imageUrl: 'https://i.ibb.co/FXhr67m/watch4.jpg',
        price: 25,
      },
      {
        id: 5,
        name: 'Watch 5',
        imageUrl: 'https://i.ibb.co/wChTXDB/watch6.jpg',
        price: 18,
      },
      {
        id: 6,
        name: 'Watch 6',
        imageUrl: 'https://i.ibb.co/jJKqzfd/watch7.jpg',
        price: 14,
      },
      {
        id: 7,
        name: 'Watch 7',
        imageUrl: 'https://i.ibb.co/sJsB7mB/watch8.jpg',
        price: 18,
      },
      {
        id: 8,
        name: 'Watch 8',
        imageUrl: 'https://i.ibb.co/qD2xG1v/watch1.jpg',
        price: 14,
      },
    ],
  },
  sneakers: {
    id: 2,
    title: 'Sneakers',
    routeName: 'sneakers',
    items: [
      {
        id: 10,
        name: 'Senakers1',
        imageUrl: 'https://i.ibb.co/2NF7zf3/sneaker8.jpg',
        price: 220,
      },
      {
        id: 11,
        name: 'Senakers2',
        imageUrl: 'https://i.ibb.co/j5Z3frj/sneaker7.jpg',
        price: 280,
      },
      {
        id: 12,
        name: 'Senakers3',
        imageUrl: 'https://i.ibb.co/jWmf6kL/sneaker6.jpg',
        price: 110,
      },
      {
        id: 13,
        name: 'Senakers4',
        imageUrl: 'https://i.ibb.co/SXK5QpY/sneaker5.jpg',
        price: 160,
      },
      {
        id: 14,
        name: 'Senakers5',
        imageUrl: 'https://i.ibb.co/Yk8WrB0/sneaker4.jpg',
        price: 160,
      },
      {
        id: 15,
        name: 'Senakers6',
        imageUrl: 'https://i.ibb.co/M7yNnVt/sneaker3.jpg',
        price: 160,
      },
      {
        id: 16,
        name: 'Senakers7',
        imageUrl: 'https://i.ibb.co/1KXPjyv/sneaker2.jpg',
        price: 190,
      },
      {
        id: 17,
        name: 'Senakers8',
        imageUrl: 'https://i.ibb.co/C26TvyN/sneaker1.jpg',
        price: 200,
      },
    ],
  },
  sunglasses: {
    id: 3,
    title: 'Sunglasses',
    routeName: 'sunglasses',
    items: [
      {
        id: 18,
        name: 'Sunglass1',
        imageUrl: 'https://i.ibb.co/HVC4vbX/sunglass14.jpg',
        price: 125,
      },
      {
        id: 19,
        name: 'Sunglass2',
        imageUrl: 'https://i.ibb.co/NrRgCDv/sunglasss13.jpg',
        price: 90,
      },
      {
        id: 20,
        name: 'Sunglass3',
        imageUrl: 'https://i.ibb.co/MN4pwLT/sunglass12.jpg',
        price: 90,
      },
      {
        id: 21,
        name: 'Sunglass4',
        imageUrl: 'https://i.ibb.co/qBKjMSY/sunglass11.jpg',
        price: 165,
      },
      {
        id: 22,
        name: 'Sunglass5',
        imageUrl: 'https://i.ibb.co/Z6Xrbtb/sunglass10.jpg',
        price: 185,
      },
      {
        id: 36,
        name: 'Sunglass6',
        imageUrl: 'https://i.ibb.co/9nnx4Vq/sunglass8.jpg',
        price: 185,
      },
      {
        id: 37,
        name: 'Sunglass7',
        imageUrl: 'https://i.ibb.co/sqjtzbT/sunglass3.jpg',
        price: 185,
      },
      {
        id: 38,
        name: 'Sunglass8',
        imageUrl: 'https://i.ibb.co/ZRQxjNF/sunglass.jpg',
        price: 185,
      },
    ],
  },
  womens: {
    id: 4,
    title: 'Women-Fashion',
    routeName: 'womens',
    items: [
      {
        id: 23,
        name: 'Women Fashion1',
        imageUrl: 'https://i.ibb.co/KLLzdSK/striped-sweater.png',
        price: 25,
      },
      {
        id: 24,
        name: 'Women Fashion2',
        imageUrl: 'https://i.ibb.co/Sw3M7sY/white-vest.png',
        price: 20,
      },
      {
        id: 25,
        name: 'Women Fashion3',
        imageUrl: 'https://i.ibb.co/9rJCX2w/women1.jpg',
        price: 80,
      },
      {
        id: 26,
        name: 'Women Fashion4',
        imageUrl: 'https://i.ibb.co/GCR2GjX/women5.png',
        price: 80,
      },
      {
        id: 27,
        name: 'Women Fashion5',
        imageUrl: 'https://i.ibb.co/N2KWWvx/women6.png',
        price: 45,
      },
      {
        id: 28,
        name: 'Women Fashion6',
        imageUrl: 'https://i.ibb.co/Sc1VjSJ/women7.png',
        price: 135,
      },
      {
        id: 29,
        name: 'Women Fashion7',
        imageUrl: 'https://i.ibb.co/5FfmcMH/women8.png',
        price: 20,
      },
      {
        id: 36,
        name: 'Women Fashion7',
        imageUrl: 'https://i.ibb.co/02VT3M7/women9.png',
        price: 20,
      },
    ],
  },
  mens: {
    id: 5,
    title: 'Men-Fashion',
    routeName: 'mens',
    items: [
      {
        id: 30,
        name: 'Men Fashion1',
        imageUrl: 'https://i.ibb.co/HKJJV5X/men1.png',
        price: 325,
      },
      {
        id: 31,
        name: 'Men Fashion2',
        imageUrl: 'https://i.ibb.co/L64whsY/men3.jpg',
        price: 20,
      },
      {
        id: 32,
        name: 'Men Fashion3',
        imageUrl: 'https://i.ibb.co/Fm46YDm/men2.jpg',
        price: 25,
      },
      {
        id: 33,
        name: 'Men Fashion4',
        imageUrl: 'https://i.ibb.co/5RnqzSr/men5.jpg',
        price: 25,
      },
      {
        id: 34,
        name: 'Men Fashion5',
        imageUrl: 'https://i.ibb.co/BLctFbz/men4.jpg',
        price: 40,
      },
      {
        id: 35,
        name: 'Men Fashion6',
        imageUrl: 'https://i.ibb.co/kGY5CxW/men6.jpg',
        price: 25,
      },
      {
        id: 35,
        name: 'Men Fashion6',
        imageUrl: 'https://i.ibb.co/V3L656m/men7.jpg',
        price: 25,
      },
      {
        id: 35,
        name: 'Men Fashion6',
        imageUrl: 'https://i.ibb.co/DQ1rGYL/men8.jpg',
        price: 25,
      },
    ],
  },

  kids: {
    id: 6,
    title: 'Kids-Fashion',
    routeName: 'kids',
    items: [
      {
        id: 39,
        name: 'Kids Fashion1',
        imageUrl: 'https://i.ibb.co/X8dfgLQ/kids1.jpg',
        price: 325,
      },
      {
        id: 40,
        name: 'Kids Fashion2',
        imageUrl: 'https://i.ibb.co/Xb7xvjT/kids2.jpg',
        price: 20,
      },
      {
        id: 41,
        name: 'Kids Fashion3',
        imageUrl: 'https://i.ibb.co/nqG0GrN/kids3.jpg',
        price: 25,
      },
      {
        id: 42,
        name: 'Kids Fashion4',
        imageUrl: 'https://i.ibb.co/4WgySf4/kids4.jpg',
        price: 25,
      },
      {
        id: 43,
        name: 'Kids Fashion5',
        imageUrl: 'https://i.ibb.co/V9V6W1K/pexels-tu-n-ki-t-jr-1374509.jpg',
        price: 40,
      },
      {
        id: 44,
        name: 'Kids Fashion6',
        imageUrl: 'https://i.ibb.co/rm74kzs/pexels-nappy-1068209.jpg',
        price: 25,
      },
      {
        id: 45,
        name: 'Kids Fashion6',
        imageUrl: 'https://i.ibb.co/MhYZXYP/pexels-janko-ferlic-4055337.jpg',
        price: 25,
      },
      {
        id: 46,
        name: 'Kids Fashion6',
        imageUrl: 'https://i.ibb.co/xh9GST8/kids5.jpg',
        price: 25,
      },
    ],
  },
};

export default SHOP_DATA;
